name: InstiApp
description: Flutter App for Indian Institute of Technology, Bombay

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.4.1+29

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.1
  url_launcher: ^6.0.17
  qr_code_scanner: ^1.0.1
  http: ^1.2.1
  rxdart: ^0.27.7
  flutter_widget_from_html_core: any
  fwfh_selectable_text: ^0.8.3
  markdown: ^7.2.2
  shared_preferences: ^2.0.10
  date_format: ^2.0.4
  share: ^2.0.4
  photo_view: ^0.15.0
  flutter_calendar_carousel: ^2.4.3
  # google_maps_flutter: ^2.1.1
  # flutter_google_places: ^0.3.0
  location: ^6.0.2
  flutter_material_color_picker: ^1.1.0+2
  flutter_typeahead: ^5.2.0
  image_picker: ^1.1.2

  firebase_messaging: ^11.2.3
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.0.8
  cached_network_image: ^3.2.0
  flutter_image_compress: ^2.3.0
  uni_links: ^0.5.1
  analyzer: ^6.4.1
  flutter_dynamic_icon: ^2.0.0
  device_calendar: ^4.2.0
  dropdown_search: ^5.0.6
  multi_select_flutter: ^4.1.3
  retrofit: ^4.1.0
  logger: any
  dio: ^5.4.3+1
  json_annotation: ^4.4.0
  jaguar: ^3.0.12
  jaguar_flutter_asset: ^3.0.0
  flutter_webview_pro: ^3.0.1+4
  home_widget: ^0.6.0
  flutter_dotenv: ^5.1.0

  permission_handler: ^11.3.1
  qr_flutter: ^4.0.0
  intl: ^0.18.1

  awesome_notifications: ^0.8.2
  flutter_linkify: ^6.0.0
  upgrader: ^10.3.0
  encrypt: ^5.0.1

  collection: any
  timezone: any
  firebase_core: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  json_model: any

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/login/
    - assets/map/
    - assets/communities/
    - assets/communities/emojis/
    - assets/map/assets/
    - assets/map/assets/map/
    - assets/buynsell/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans/IBMPlexSans-Italic.ttf
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: fonts/IBMPlexSans/IBMPlexSans-BoldItalic.ttf
          style: italic
          weight: 700
    - family: LostAndFoundIcon
      fonts:
        - asset: fonts/LostAndFoundIcon.ttf
  uses-material-design: true
# targets:
#   $default:
#     builders:
#       json_serializable:
#         options:
#           # Options configure how source code is generated for every
#           # `@JsonSerializable`-annotated class in the package.
#           #
#           # The default value for each is listed.
#           any_map: false
#           checked: false
#           constructor: ""
#           create_factory: true
#           create_to_json: true
#           disallow_unrecognized_keys: false
#           explicit_to_json: false
#           field_rename: none
#           generic_argument_factories: false
#           ignore_unannotated: false
#           include_if_null: true

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  firebase_crashlytics_platform_interface: 3.1.13
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  firebase_analytics_platform_interface: 3.0.5
  firebase_remote_config_platform_interface: 1.0.5
  firebase_dynamic_links_platform_interface: 0.2.0+5
  firebase_performance_platform_interface: 0.1.0+5
  firebase_app_installations_platform_interface: 0.1.0+6
  firebase_core_platform_interface: 4.2.2